### ISSUE TITLE
Recode all the generators in Jinja

### ISSUE THREAD

**Issue by seirl** [prologin/stechec2#45]
## Misc generators

- [x] Règles (@Shaac) : #66 
- [x] Sphinx (@seirl) : c6122bde16064975062d86133527c279375b3895
- [x] Texdoc (@seirl) : 8b7542a2147839e06573702aee5a2294643b066c

## Champions

- [x] C++ (@Shaac) : #75 
- [x] C (@seirl) : #76 
- [x] Python (@seirl) : #83 
- [x] PHP (@seirl) : #84 
- [x] Java (@Shaac) : #90 
- [x] OCaml (@Dettorer) : #97
- [x] C# (@alarsyo) : #110 
- [x] Haskell (@zuh0) : #98 
- [x] Rust (@remi-dupre) : #85 

## Other

- [x] Test loading (@seirl) : #80 
- [x] Test champions (@seirl) : c09a648
- [x] Server makefiles (@seirl) : #92 
- [x] Symlinks (@seirl) : #93

## Minor issues
- [ ] Inline api.h in the C API so that the `interface.cc` is self-sufficient for languages that depend on it
- [x] Load the correct `cst_type` directly when loading the constants in `game.py` instead of having to call a helper (#114)
- [x] Load the `afficher_*` functions (with a special attribute like `fct_display: true` so that we can filter them out if necessary) (#113)
- [x] Filter out reserved language keywords while loading the YAML (#109)

**Comment by alarsyo** [comment]
Could you add me on the C# and Go champions generators ? :)
